version: "3.8"
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_gentures
    ports:
      - "3307:3306"
